### ISSUE TITLE
hanging after attempting to download snapshot

### ISSUE THREAD

**Issue by RibDibBibarel** [iron-fish/node-app#227]
Using v1.01. Created a wallet, had to restart app to get to UI, was asked to download snapshot, app has been hanging ever since.

**Comment by nasvuazi** [comment]
Установил новый кошелёк. Так же висит на логотипе.

**Comment by geoffwade** [comment]
Although I'm unable to find release notes mentioning this, I believe it's because mainnet is not live yet.   the GUI wallet is a quick way to get a wallet address.   I would use node wallet if you plan on mining immediately when mainnet goes live or just use GUI created wallet and they will certainly sort out the issues soon enough to access coins you have mined.

**Comment by jez-bo** [comment]
> Although I'm unable to find release notes mentioning this, I believe it's because mainnet is not live yet. the GUI wallet is a quick way to get a wallet address. I would use node wallet if you plan on mining immediately when mainnet goes live or just use GUI created wallet and they will certainly sort out the issues soon enough to access coins you have mined.

Can't get pass the hanging logo to even see the public address. Anyone know a work-around?

**Comment by geoffwade** [comment]
> > Although I'm unable to find release notes mentioning this, I believe it's because mainnet is not live yet. the GUI wallet is a quick way to get a wallet address. I would use node wallet if you plan on mining immediately when mainnet goes live or just use GUI created wallet and they will certainly sort out the issues soon enough to access coins you have mined.
> 
> Can't get pass the hanging logo to even see the public address. Anyone know a work-around?
I just updated my post... delete the Chain directory

**Comment by jez-bo** [comment]
> > > Although I'm unable to find release notes mentioning this, I believe it's because mainnet is not live yet. the GUI wallet is a quick way to get a wallet address. I would use node wallet if you plan on mining immediately when mainnet goes live or just use GUI created wallet and they will certainly sort out the issues soon enough to access coins you have mined.
> > 
> > 
> > Can't get pass the hanging logo to even see the public address. Anyone know a work-around?
> > I just updated my post... delete the Chain directory

Thank you! this worked!

**Comment by RibDibBibarel** [comment]
> > > Although I'm unable to find release notes mentioning this, I believe it's because mainnet is not live yet. the GUI wallet is a quick way to get a wallet address. I would use node wallet if you plan on mining immediately when mainnet goes live or just use GUI created wallet and they will certainly sort out the issues soon enough to access coins you have mined.
> > 
> > 
> > Can't get pass the hanging logo to even see the public address. Anyone know a work-around?
> > I just updated my post... delete the Chain directory

Just following up, this worked for me too. It makes sense as an explanation and solution too.

**Comment by Kujira-WhaleHunter** [comment]
> > > Although I'm unable to find release notes mentioning this, I believe it's because mainnet is not live yet. the GUI wallet is a quick way to get a wallet address. I would use node wallet if you plan on mining immediately when mainnet goes live or just use GUI created wallet and they will certainly sort out the issues soon enough to access coins you have mined.
> > 
> > 
> > Can't get pass the hanging logo to even see the public address. Anyone know a work-around?
> > I just updated my post... delete the Chain directory

....and where would i find Chain Directory ? i'm stuck with staring at ÏRON FISH after snapshot download? bahh

**Comment by geoffwade** [comment]
> 

C:\Users\myname\.ironfish\databases\chain

**Comment by nasvuazi** [comment]
> Хотя я не могу найти упоминания об этом в примечаниях к выпуску, я полагаю, это потому, что mainnet еще не запущен. кошелек с графическим интерфейсом - это быстрый способ получить адрес кошелька. Я бы использовал node wallet, если вы планируете майнинг сразу после запуска mainnet или просто используете созданный в графическом интерфейсе адрес кошелька, и они, безусловно, решат проблемы достаточно скоро, чтобы получить доступ к добытым вами монетам. Чтобы восстановить работу кошелька с графическим интерфейсом, вы можете удалить каталог 'chain', расположенный здесь C:\Users\myname.ironfish\databases\chain а затем откройте резервную копию кошелька с графическим интерфейсом. Не загружайте снимок снова, пока проблема не будет решена.

Работает!
